server:
  port: 0000

spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  application:
    name: user-service

env:
  message: Greeting

eureka:
  instance:
    instanceId: ${spring.application.name}:${random.value}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

token:
  expiration_time: 600000
  secret: mPz6K217B4v8rK7YuG1d0kZ1R5yW9aqSfdsasgw45646546agdfdsbx